# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:

- task: Go@0
  inputs:
    command: 'get'
  displayName: 'Get dependencies, then build'

- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o main'
  displayName: 'build go project'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(96f7d97d-4572-4105-afe7-7a03a7a8f3a3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az help'
