# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:

- task: Go@0
  inputs:
    command: 'get'
  displayName: 'Get dependencies, then build'

- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o main'
  displayName: 'build go project'

- bash: |
    mkdir function
    cp host.json function/
    cp -R foo function/
    cp main function/

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './function'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- bash: ls -l .
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(96f7d97d-4572-4105-afe7-7a03a7a8f3a3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config storage-account update -g $(RESOURCE_GROUP_NAME) -n $(FUNCTION_NAME) \
      --custom-id $(FUNCTION_NAME) \
      --storage-type AzureFiles \
      --account-name $(STORAGE_ACCOUNT_NAME) \
      --share-name $(FILESHARE_NAME) \
      --access-key $(STORAGE_ACCOUNT_ACCESS_KEY) \
      --mount-path /var/opt
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(96f7d97d-4572-4105-afe7-7a03a7a8f3a3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az functionapp config appsettings set \
      --name $(FUNCTION_NAME) \
      --resource-group $(RESOURCE_GROUP_NAME) \
      --settings "CONFIG_PATH=/var/opt/foo.json"